name: Azure CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  # Frontend deployment job for Static Web App
  frontend_build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend (Static Web App)
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy Frontend
        id: builddeployfrontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MUD_03B04A71E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Used for Github integrations (PR comments)
          action: "upload"
          app_location: "./frontend"  # Path to your frontend app (HTML, JS, CSS)
          api_location: ""  # Leave empty for a Static Web App if no backend is directly in the repo
          output_location: "."  # Built app content directory

  # Backend deployment job for Azure App Service (Flask API)
  backend_deploy:
    runs-on: ubuntu-latest
    name: Deploy Backend to Azure App Service
    needs: frontend_build_and_deploy  # Make sure backend deployment happens after frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version you want to use
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Update this path if needed
      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'video-backend-xyz'  # Replace with your backend App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Use publish profile stored in GitHub Secrets
          package: './backend'  # Path to your backend folder (Flask app)

  # Close Pull Request job (if a PR is closed)
  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MUD_03B04A71E }}
          action: "close"
